apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: healthcare
  namespace: argocd
spec:
  description: "ArgoCD Project for ElderPinq Healthcare and Platform workloads"
  sourceRepos:
    - '*'
  destinations:
    - namespace: healthcare
      server: https://kubernetes.default.svc
    - namespace: platform
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: security
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
