apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: "ArgoCD Project for EKS Infrastructure Platform Controllers"
  sourceRepos:
    - '*'
  destinations:
    - namespace: platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
