# Dev environment values override
replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  environment: "dev"
  dbHost: "finops-db-dev"
  dbName: "finops_db_dev"

