apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace | default "healthcare" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: elderpinq-secrets-store
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: elderpinq/{{ .Values.env.environment | default "dev" }}/db
        property: password
    - secretKey: jwt-secret
      remoteRef:
        key: elderpinq/{{ .Values.env.environment | default "dev" }}/jwt
        property: secret
