# Staging environment values override
replicaCount: 2

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  environment: "staging"
  dbHost: "alert-db-staging"
  dbName: "alert_db_staging"

